### PR TITLE
Added common phpmyadmin locations. phpmyadmin shouldn't be accessible…

### PR DESCRIPTION
**Pull request by JosephGregg**
… as it could lead to deanonymization. I used the formatting that you had suggested in issue #1. Please let me know if this is what you had in mind. Thanks!

### CODE REVIEW

**Comment by JosephGregg** [comment]
My apologies for the first request. I've removed the redundant contains value.

**Comment by s-rah** [comment]
Hi, Thanks this is looking awesome! 

One thing that we need to add is a documentation config, something like:

```
{ 
     "name":"phpMyAdmin is Accessible",
     "why-this-is-bad":"the exposure of phpMyAdmin portal......",
     "to-fix":"Make sure phpMyAdmin portals aren't exposed......"
    "ruleset": <your large array of locations>
}
```

Need to work through exactly what that should look like.

**Comment by JosephGregg** [comment]
Understood. Let me see what I can come up with. Thanks again for this awesome project! Motivated me to contribute back to the community.

**Comment by s-rah** [comment]
Closing until, we have better idea about how to pull this in.

**Pull request closed without merging**
