### PR TITLE
Grab date/time from http headers

### PR DESCRIPTION
**Pull request by JosephGregg**
Server may reveal locality based on timestamp in headers.

### CODE REVIEW

**Comment by s-rah** [comment]
Can we make this more useful? The Date header is nice, but to be useful to the reporting we should try to make it more concrete e.g. ServerReportedTimezone: UTC-5

**Comment by PeterTonoli** [comment]
hi, for an attack to be effective on hidden services, using HTTP timestamps as a vector, the timezone isn't necessarily required.

Deanonymisation via clock-skew detection, as explained in [http://sec.cs.ucl.ac.uk/users/smurdoch/papers/usenix08clockskew.pdf](An Improved Clock-skew Measurement Technique
for Revealing Hidden Services), just the timestamp is adequate enough.

**Comment by s-rah** [comment]
Thanks for the link @PeterTonoli, awesome point.

@JosephGregg let's keep the Date header output as is, and also extract timezone.

We should probably start collecting these kinds of papers somewhere, it would be nice to link them from the source.

**Comment by s-rah** [comment]
Hey @JosephGregg any progress on this?

**Comment by s-rah** [comment]
Headers are currently pulled out. We can revisit this at some point during analysis.

**Pull request closed without merging**
